add gfwlist

diff --git a/armv7_shadowsocks/ss-rules b/armv7_shadowsocks/ss-rules
--- a/armv7_shadowsocks/ss-rules
+++ b/armv7_shadowsocks/ss-rules
@@ -8,7 +8,7 @@
 #
 
 #debug
-#set -x
+set -x
 
 TAG="SS_SPEC"          # iptables tag
 IPT="iptables -t nat"  # alias of iptables
@@ -33,6 +33,7 @@ usage() {
 		    -u                      enable udprelay mode, TPROXY is required
 		    -U                      enable udprelay mode, using different IP
 		                            and ports for TCP and UDP
+		    -G                      enable GFWLIST
 		    -f                      flush the rules
 		    -h                      show this help message and exit
 EOF
@@ -51,14 +52,22 @@ flush_r() {
 	-e 's/-A INPUT -i br0 -m state -j ACCEPT/-A INPUT -i br0 -m conntrack --ctstate NEW -j ACCEPT/' \
 	-e 's/-A FORWARD -m state -j ACCEPT/-A FORWARD -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT/' \
 	-e 's/-A FORWARD -i br0 -m state -j ACCEPT/-A FORWARD -i br0 -m conntrack --ctstate NEW -j ACCEPT/' | \
-	grep -v "$TAG" | \
+	grep -v "$TAG" | grep -v "gfw_black_list" | \
 	iptables-restore -c 2>/dev/null
 	$IPT -F
 	ip rule del fwmark 0x01/0x01 table 100 2>/dev/null
 	ip route del local 0.0.0.0/0 dev lo table 100 2>/dev/null
 	ipset -X ss_spec_lan_ac 2>/dev/null
 	ipset -X ss_spec_wan_ac 2>/dev/null
-	our_rule	
+	ipset -X gfw_black_list 2>/dev/null	
+	our_rule
+	if [ "$GFWLIST" = 1 ]; then
+		ipset -N gfw_black_list hash:ip
+		$IPT -A PREROUTING -p tcp -m set --match-set gfw_black_list dst \
+			-j REDIRECT --to-port `sed -n 's/.*l_port":\(.*\)/\1/p' /opt/etc/shadowsocks.json | sed 's/,//g'`
+		$IPT -A OUTPUT -p tcp -m set --match-set gfw_black_list dst \
+			-j REDIRECT --to-port `sed -n 's/.*l_port":\(.*\)/\1/p' /opt/etc/shadowsocks.json | sed 's/,//g'`
+	fi	
 	return 0
 }
 
@@ -92,10 +101,7 @@ our_rule() {
 	$IPT -t nat -A POSTROUTING -s `nvram get lan_ipaddr | sed -e 's;1$;0/24;'` -o ppp0 \
 		-j SNAT --to-source `nvram get wan_ipaddr` && \
 	$IPT -t nat -A POSTROUTING -m mark --mark 0x80000000/0x80000000 \
-		-j MASQUERADE 2>/dev/null || {
-		loger 3 "Can't redirect, please check the iptables."
-		exit 1
-	}
+		-j MASQUERADE
 	return $?
 }
 
@@ -172,7 +178,7 @@ gen_iplist() {
 EOF
 }
 
-while getopts ":s:l:S:L:i:e:a:b:w:ouUfh" arg; do
+while getopts ":s:l:S:L:i:e:a:b:w:ouUGfh" arg; do
 	case "$arg" in
 		s)
 			server=$OPTARG
@@ -210,6 +216,9 @@ while getopts ":s:l:S:L:i:e:a:b:w:ouUfh" arg; do
 		U)
 			TPROXY=2
 			;;
+		G)
+			GFWLIST=1
+			;;			
 		f)
 			flush_r
 			exit 0
@@ -220,8 +229,12 @@ while getopts ":s:l:S:L:i:e:a:b:w:ouUfh" arg; do
 	esac
 done
 
-if [ -z "$server" -o -z "$local_port" ]; then
-	usage 2
+if [ "$GFWLIST" = 1 ]; then
+	logger [GFWLIST] ok
+else
+	if [ -z "$server" -o -z "$local_port" ]; then
+		usage 2
+	fi
 fi
 
 if [ "$TPROXY" = 1 ]; then
@@ -232,6 +245,12 @@ elif [ "$TPROXY" = 2 ]; then
 	: ${LOCAL_PORT:?"You must assign a port for the udp relay server."}
 fi
 
-flush_r && fw_rule && ipset_r && ac_rule && tp_rule
-[ "$?" = 0 ] || logger 3 "Start failed!"
-exit $?
+if [ -f "$IGNORE_LIST" ]; then
+	flush_r && fw_rule && ipset_r && ac_rule && tp_rule
+	[ "$?" = 0 ] || logger 3 "Start failed!"
+	exit $?
+else
+	flush_r
+	[ "$?" = 0 ] || logger 3 "Start failed!"
+	exit $?
+fi
